# Generated by Django 4.0 on 2021-12-17 13:00

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('std_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('std_address', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=app1.models.filepath)),
            ],
        ),
    ]
