# Generated by Django 4.0 on 2021-12-17 13:26

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=app1.models.filepath),
        ),
    ]
